# Generated by Django 5.1.3 on 2024-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_remove_tweet_retweets_retweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='retweeted_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
