# Generated by Django 5.1.3 on 2024-12-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_tweet_retweeted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='retweet',
            name='retweeted_tweet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet.tweet'),
        ),
    ]
