# Generated by Django 5.1.3 on 2024-12-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_tweet_replied_to_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.TextField()),
                ('tweets', models.ManyToManyField(to='tweet.tweet')),
            ],
        ),
    ]
