# Generated by Django 5.1.3 on 2025-01-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0009_alter_tweet_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='replied_to',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweeted_by',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
