# Generated by Django 5.1.3 on 2025-01-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0010_alter_tweet_options_alter_tweet_replied_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='replied_to',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweeted_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
