# Generated by Django 5.1.3 on 2024-12-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='banners/default.jpeg', upload_to='banners'),
        ),
    ]
